# nixpacks.toml

providers = ["python"]

[phases.setup]
nixPkgs = ["prisma"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["prisma generate"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port 3000"
