# nixpacks.toml

providers = ['python']

[phases.setup]
nixpkgs = ["python312", "openssl", "pkg-config"]
aptPkgs = ["libssl-dev"]

[phases.install]
cmds = [
  "pip3 install -r requirements.txt",
  "prisma generate"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port 3000"